### ISSUE TITLE
copy/pasted youtube url not working

### ISSUE THREAD

**Issue by Raven24** [judofyr/ruby-oembed#21]
I suppose it should be possible for people to be able to use the youtube link they see in the browser for copy&pasting. E.g.

`http://www.youtube.com/watch?feature=player_embedded&v=SUTBdArjxFo`

yields the following error:

```
$> OEmbed::Providers.get "http://www.youtube.com/watch?feature=player_embedded&v=SUTBdArjxFo"
OEmbed::NotFound: No embeddable content at 'http://www.youtube.com/watch?feature=player_embedded&v=SUTBdArjxFo'
        from /home/florian/.rvm/gems/ruby-1.9.2-p290@diaspora/gems/ruby-oembed-0.8.7/lib/oembed/provider.rb:149:in `raw'
        from /home/florian/.rvm/gems/ruby-1.9.2-p290@diaspora/gems/ruby-oembed-0.8.7/lib/oembed/provider.rb:84:in `get'
        from /home/florian/.rvm/gems/ruby-1.9.2-p290@diaspora/gems/ruby-oembed-0.8.7/lib/oembed/providers.rb:102:in `get'
        from (irb):4
        from /home/florian/.rvm/gems/ruby-1.9.2-p290@diaspora/gems/railties-3.1.4/lib/rails/commands/console.rb:45:in `start'
        from /home/florian/.rvm/gems/ruby-1.9.2-p290@diaspora/gems/railties-3.1.4/lib/rails/commands/console.rb:8:in `start'
        from /home/florian/.rvm/gems/ruby-1.9.2-p290@diaspora/gems/railties-3.1.4/lib/rails/commands.rb:40:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

I'm not sure if this is a limitation by the Youtube oEmbed API or something else...
(This issue originally came up here: https://github.com/diaspora/diaspora/issues/3025 )

**Comment by drewish** [comment]
Seems like this could be closed?

**Comment by metavida** [comment]
Confirmed that the latest version of ruby-oembed correctly takes care of URL parameter escaping. Thanks for the bump @drewish!

```ruby
> OEmbed::VERSION #=> "0.9.0" 
> OEmbed::Providers.register_all #=> [] 
> OEmbed::Providers.get "http://www.youtube.com/watch?feature=player_embedded&v=SUTBdArjxFo"
# => #<OEmbed::Response::Video:0x007f81ed05ba88 @fields={"html"=>"<iframe ... @format="json"> 
```
