### ISSUE TITLE
Incompatible with Ruby 2.2

### ISSUE THREAD

**Issue by jxpx777** [judofyr/ruby-oembed#43]
Run the following code in 2.1.x and 2.2.

```
require 'rubygems'
require 'openssl'
require 'oembed'

provider = OEmbed::Providers::Vimeo.get("http://vimeo.com/113057654")
puts provider.html
```

In Ruby 2.1.4, I get successful HTML output:
```
"<iframe src=\"//player.vimeo.com/video/113057654\" width=\"1280\" height=\"720\" frameborder=\"0\" title=\"Gingerbread House 2014\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>"
```

In Ruby 2.2.0, I get this error:
```
/Users/j/.rbenv/versions/2.2.0/lib/ruby/2.2.0/uri/generic.rb:743:in `registry=': can not set registry (URI::InvalidURIError)
	from /Users/j/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/ruby-oembed-0.8.11/lib/oembed/provider.rb:138:in `block in raw'
	from /Users/j/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/ruby-oembed-0.8.11/lib/oembed/provider.rb:138:in `each'
	from /Users/j/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/ruby-oembed-0.8.11/lib/oembed/provider.rb:138:in `raw'
	from /Users/j/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/ruby-oembed-0.8.11/lib/oembed/provider.rb:86:in `get'
	from /Users/j/Desktop/ruby-oembed-test.rb:5:in `<main>'
```

**Comment by jxpx777** [comment]
My pleasure! Glad the fix is in the offing.

**Comment by metavida** [comment]
Alrighty. Version 0.8.12 of ruby-oembed (with Ruby 2.2 support) is now on rubygems.

**Comment by benwalsh** [comment]
I'm still seeing this issue with version `0.8.14` and ruby `2.2.3`

```
 >> OEmbed::Providers::Youtube.get("https://youtu.be/blSl487coFg")
URI::InvalidURIError: can not set registry
from /home/vagrant/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/uri/generic.rb:743:in `registry='
```

```
$ gem list oembed

*** LOCAL GEMS ***

ruby-oembed (0.8.14)
```

**Comment by metavida** [comment]
@benwalsh I'm not able to reproduce that error locally. Could you help me troubleshoot a bit? Here's what I'm seeing:

```ruby
# Started an irb session using: bundle exec irb
require 'oembed' #=> true 
OEmbed::VERSION #=> "0.8.14" 
RUBY_VERSION #=> "2.2.3" 
RUBY_VERSION < "2.2" #=> false 
OEmbed::Providers::Youtube.get("https://youtu.be/blSl487coFg") #=> #<OEmbed::Response::Video:0x007fa48425dd40 @fields={"version"=>"1.0", "provider_name"=>"YouTube" ...
```

I know that in 0.8.14 we added [a conditional on the `RUBY_VERSION` constant](https://github.com/judofyr/ruby-oembed/blob/v0.8.14/lib/oembed/provider.rb#L138-L143) that controls whether or not the gem tries to set the `registry` attribute on `URI` instances. Maybe `RUBY_VERSION` in your app/context is returning an unusual value?

**Comment by benwalsh** [comment]
@metavida thank you -- that's what it was, I guess that `RUBY_VERSION` had persisted at some point when switching `rvm`s. Working now!
